version: 2

seeds:
  - name: employees
    description: a manula map of employees to customers
    columns:
      - name: employee_id
        tests:
            - unique
            - not_null